---

- name: update the motd/issue files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - src: motd.j2
      dest: /etc/motd

    - src: motd.j2
      dest: /etc/issue